In [1]:
from feast import FeatureStore 
import pandas as pd

In [6]:
FEATURE_STORE_PATH = "../feature_store/house_features/feature_repo/"

In [ ]:
store = FeatureStore(repo_path=FEATURE_STORE_PATH)

entity_df = pd.DataFrame.from_dict({"house_id": [1,2,3], "event_timestamp": pd.to_datetime(["now","now","now"])})

   house_id            event_timestamp
0         1 2026-03-11 11:04:33.024076
1         2 2026-03-11 11:04:33.024212
2         3 2026-03-11 11:04:33.024215

In [9]:
features = store.get_historical_features(entity_df=entity_df, features=["house_features:sqft", "house_features:bedrooms"])
features.to_df()

   house_id                  event_timestamp  sqft  bedrooms
0         1 2026-03-11 11:04:33.024076+00:00  1200         2
1         2 2026-03-11 11:04:33.024212+00:00  1500         3
2         3 2026-03-11 11:04:33.024215+00:00   900         2